name: capstone2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1

  cloud_firestore: ^5.6.5

  qr_flutter: ^4.1.0


  firebase_auth: ^5.5.1

  http: ^1.3.0

  fluentui_system_icons: ^1.1.0 


  cupertino_icons: ^1.0.8


  fluentui_icons: ^1.0.0
  board_datetime_picker: ^2.5.0

  qr_code_scanner_plus: ^2.0.10+1
  url_launcher: ^6.3.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/images/
    
