// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5LdWbcbDdY7FksFQ2wyRlmnYNJKduGBg',
    appId: '1:977188120159:web:35d59ea54ddb62f4bb1dea',
    messagingSenderId: '977188120159',
    projectId: 'capstone2-41149',
    authDomain: 'capstone2-41149.firebaseapp.com',
    storageBucket: 'capstone2-41149.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD0MEkALLIClLiUCJxY2YSB-V4p5DjO9I',
    appId: '1:139211941947:android:f3408539e3597b7d66941e',
    messagingSenderId: '139211941947',
    projectId: 'busbus-c4071',
    storageBucket: 'busbus-c4071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5zv9LWPeMXODH9opH3HK0WvqNAPOPWY',
    appId: '1:139211941947:ios:670be4687ba2e4dc66941e',
    messagingSenderId: '139211941947',
    projectId: 'busbus-c4071',
    storageBucket: 'busbus-c4071.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiId9-lnRhthKbL4rINwOe68eOM8OpGNY',
    appId: '1:977188120159:ios:b525f14f79db1e6fbb1dea',
    messagingSenderId: '977188120159',
    projectId: 'capstone2-41149',
    storageBucket: 'capstone2-41149.appspot.com',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5LdWbcbDdY7FksFQ2wyRlmnYNJKduGBg',
    appId: '1:977188120159:web:2a8fa63d86a2fd1abb1dea',
    messagingSenderId: '977188120159',
    projectId: 'capstone2-41149',
    authDomain: 'capstone2-41149.firebaseapp.com',
    storageBucket: 'capstone2-41149.appspot.com',
  );
}